[package]
name = "urlshortner"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
dashmap = "6.1.0"
nanoid = "0.4.0"
serde = "1.0.215"
tokio = { version = "1.41.1", features = ["full"] }
tower-http = "0.6.2"
tracing-subscriber = "0.3.19"

[workspace]
